export const utils = {
    enumMappings: {
        WHITE: "White",
        BLACK: "Black",
        GRAY: "Gray",
        TAN: "Tan",
        BROWN: "Brown",
        BLUE: "Blue",
        NAVY: "Navy",
        RED: "Red",
        YELLOW: "Yellow",
        ORANGE: "Orange",
        PINK: "Pink",
        GREEN: "Green",
        PURPLE: "Purple",
        CLEAR: "Clear",
        SOFA: "Sofa",
        BEDFRAME: "Bedframe",
        DRESSER: "Dresser",
        TABLE: "Table",
        NIGHTSTAND: "NightStand",
        BOOKCASE: "Bookcase",
        DESK: "Desk",
        CHAIR: "Chair",
        ACCENT_CHAIR: "Accent Chair",
        DINING_CHAIR: "Dining Chair",
        OFFICE_CHAIR: "Office Chair",
        LOVESEAT: "Loveseat",
        SECTIONAL: "Sectional",
        MODULAR: "Modular",
        COFFEE_TABLE: "Coffee Table",
        SIDE_TABLE: "Side Table",
        DINING_TABLE: "Dining Table",
        END_TABLE: "End Table",
        PLATFORM_BED: "Platform Bed",
        TWIN: "Twin", 
        FULL: "Full", 
        QUEEN: "Queen", 
        KING: "King", 
        CALIFORNIA_KING: "California King", 
        MODERN: "Modern",
        MINIMAL: "Minimal",
        RUSTIC: "Rustic",
        CONTEMPORARY: "Contemporary",
        INDUSTRIAL: "Industrial",
        MID_CENTURY_MODERN: "Mid Century Modern",
        TRADITIONAL: "Traditional",
        SCANDINAVIAN: "Scandinavian",
        BOHEMIAN: "Bohemian",
        LIVING_ROOM: "Living Room",
        BEDROOM: "Bedroom",
        DINING_ROOM: "Dining Room",
        KITCHEN: "Kitchen",
        HOME_OFFICE: "Home Office",
        ENTRYWAY: "Entryway",
        BATHROOM: "Bathroom",
        PATIO: "Patio",
        WOOD: "Wood",
        FABRIC: "Fabric",
        METAL: "Metal",
        LEATHER: "Leather",
        GLASS: "Glass",
        PLASTIC: "Plastic",
        UPHOLSTERY: "Upholstery"
    }, 
    options: {
        color: [
          "White",
          "Black",
          "Gray",
          "Tan",
          "Brown",
          "Blue",
          "Navy",
          "Red",
          "Yellow",
          "Orange",
          "Pink",
          "Green",
          "Purple",
          "Clear",
        ],
        type: [
          "Sofa",
          "Bedframe",
          "Dresser",
          "Table",
          "NightStand",
          "Bookcase",
          "Desk",
          "Chair"
        ],
        subType: [
          "Accent Chair",
          "Dining Chair",
          "Office Chair",
          "Loveseat",
          "Sectional",
          "Modular",
          "Coffee Table",
          "Side Table",
          "Dining Table",
          "End Table",
          "Platform Bed",
        ],
        bedSize: ["Twin", "Full", "Queen", "King", "California King"],
        style: [
          "Modern",
          "Minimal",
          "Rustic",
          "Contemporary",
          "Industrial",
          "Mid Century Modern",
          "Traditional",
          "Scandinavian",
          "Bohemian",
        ],
        room: [
          "Living Room",
          "Bedroom",
          "Dining Room",
          "Kitchen",
          "Home Office",
          "Entryway",
          "Bathroom",
          "Patio",
        ],
        material: [
          "Wood",
          "Fabric",
          "Metal",
          "Leather",
          "Glass",
          "Plastic",
          "Upholstery",
        ],
        hasStorage: ["TRUE", "FALSE"],
      }
}