name: server-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run:  mvn -B package --file server/pom.xml
      env: 
        MONGODB_USER: ${{ secrets.server-build.MONGODB_USER }}
        MONGODB_CLUSTER: ${{ secrets.server-build.MONGODB_CLUSTER }}
        MONGODB_PASSWORD: ${{ secrets.server-build.MONGODB_PASSWORD }}
